### ISSUE TITLE
Some

### ISSUE THREAD

**Issue by Echoloria** [romanhaa/cerebroApp#34]

**Comment by Echoloria** [comment]
Hi Michael @mihem,

     I'm reading your paper "Neurological Manifestations of COVID-19 Feature T Cell Exhaustion and Dedifferentiated Monocytes in Cerebrospinal Fluid", I find the raw data you uploaded to SRA database are .bam.1 format, before I try to analyze these Sc-RNAseq data  by cellranger, I transformed them into fastaq, and finally I got two filefolders in each sample, a bigger one containing more fastqs, and a smaller one containing fewer fastqs.
like this:
![图片](https://user-images.githubusercontent.com/36149883/209262309-891ecf75-d2e8-4a97-bf3c-25e063135f7c.png)

    After analyzing these data by cellranger, there are two different matrix for these two folders.
 
    Here is the question: what's the relationship between these two filefolders, hoe could I get the right gene matrix for each sample?

    Thanks for your help!

Echo

**Comment by mihem** [comment]
Hi Echo,

this is not really the right place because this is about issues with CerebroApp developed by Roman.
Just contact me via mheming.de

But maybe this helps others.
I agree I also find SRA hard to work with.
If you just want the gene matrix why don't you just download these from GEO?
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE163005

Just download barcodes, matrix and genes (all samples aggregated by cellranger there) and in combination with my annotations, which you'll also find there, you should be able to select the samples that you want.

Hope this helps,
Mischko
